#+TITLE: The Juice Bar™

Welcome to the Juice Bar™, the robotic SF Juice Bar!
Our Juicer robot is not feeling well and we would like like you to take a look at it.
We will show you its proprietary super secret source code in a minute.
But first, some background on our Juices and Happy Hours.

* OUR JUICES

We focus on quality over quantity, so we serve only 4 kinds of freshly squeezed, organic
Juice, each with a different price.

- Beet Juice :: $5.00
- Cleansing Shot (mostly water, don't tell anyone) :: $3.00
- Mangohattan :: $7.00
- Mangotini :: $7.00


* OUR HAPPY HOURS

Each happy hour happens at a different time and has its own special rules.

- Half price on mango drinks (Mangohattan and Mangotini) :: runs from 14:00 until 16:00.
- Free Cleansing Shot with Beet Juice :: runs from 20:00 until 22:00.


* THE JUICER ROBOT

The robot gets an order and a time for that order, like this:
#+BEGIN_SRC ruby
juicer_gimme({ 'Beet Juice' => 1, 'Mangohattan' => 2 }, '12:35'])
#+END_SRC
And it should return the drinks, and the bill, like this:
#+BEGIN_SRC ruby
[['Beet Juice', 'Mangohattan', 'Mangohattan'], 19.0]
#+END_SRC


* PRIMARY MISSION

Could you look at the source code and refactor it?
It works well enough (all of the specs pass), but the robot's AI says that it feels dirty inside.
There is no need to keep the existing code, as long as tests pass you can safely assume it is correct.

* SECONDARY MISSION

Now that you have successfully updated our robot, we have an additional task for you.
Our juice bar would like to run a new type of promotion which is valid for the first 30 mintes of every even hour.
During this promotion customers can purchase two mango drinks for $10

- Two mango drinks (Mangohattan or Mangotini), for $10.00. :: All day each even hour between HH:00 and HH:30
